# accessible as site.*
title: "In Valid Logic"
description: "Endlessly expanding technology"
url: "http://invalidlogic.com"
author: "Ken Robertson"
email: "ken@invalidlogic.com"

# turn on pygment syntax highlighting
pygments: true

# pagination
# paginate: 8

## permalink style: http://wiki.github.com/mojombo/jekyll/permalinks
permalink: pretty

# use rdiscount for markdown
markdown: rdiscount

# maruku settings
maruku:
  png_dir: files/latex
  png_url: /images/latex